let searchable = [

`PRODUCT NAME: AVOCOMB-E TABLETS (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 600MG,LAMIVUDINE 150MG,STAVUDINE 300MG
&lt;br&gt;
NAFDAC REG: 04-8851` ,

`PRODUCT NAME: CLARION MAX OMEGA CAPSULES (OTC)
ACTIVE INGREDIENTS: EICOSAPENTANOIC ACID 180MG,DECOSAHEXAENOIC ACID
120MG
&lt;br&gt;
NAFDAC REG: A4-3869` ,

`PRODUCT NAME: HYPERNONE POWDER
ACTIVE INGREDIENTS: EKEBERGIA SENEGALENSIS 20%, KHAYA GRANDIFOLIA 40%,
PLUMBAGO
ZEYLANICA 40%
&lt;br&gt;
NAFDAC REG: A7-0361L` ,

`PRODUCT NAME: OOSA COLINE POWDER
ACTIVE INGREDIENTS: EKEBERGIA SENEGALENSIS 20%, KHAYA GRANDIFOLIA 40%,
PLUMBAGO
ZEYLANICA 40%
&lt;br&gt;
NAFDAC REG: A7-0359L` ,
`PRODUCT NAME: TO-TO SKIN CARE 40G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,PARAFFIN,COLOURANT YELLOW B 1122040,TITANIUM
DIOXIDE,ASH,FRAGRANCE
&lt;br&gt;
NAFDAC REG: 04-4898L` ,

`PRODUCT NAME: TO-TO SKIN CARE 60G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,PARAFFIN,COLOURANT YELLOW B 1122040,TITANIUM
DIOXIDE,ASH,FRAGRANCE
&lt;br&gt;
NAFDAC REG: 04-4898L` ,

`PRODUCT NAME: TO-TO SKIN CARE(WITH SULPHUR) 40G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,PARAFFIN,COLOURANT YELLOW B 1122040,TITANIUM
DIOXIDE,SULPHUR

&lt;br&gt;
NAFDAC REG: 04-4899L` ,

`PRODUCT NAME: TO-TO SKIN CARE(WITH SULPHUR) 60G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,PARAFFIN,COLOURANT YELLOW B 1122040,TITANIUM
DIOXIDE,SULPHUR
&lt;br&gt;
NAFDAC REG: 04-4899L` ,

`PRODUCT NAME: TO-TO SKIN SOAP 75G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,SUN
SCREEN AGENT LIPEX 205,LIPEX 102
&lt;br&gt;
NAFDAC REG: 04-4901L` ,

`PRODUCT NAME: TO-TO HEALTH 20 &amp; 60G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,TRECULIA AFRICANA,RAUWOLFIA VORMIORI,TETRALEURA
TETRAPTERA, COLOURANT
BLUE C309006
&lt;br&gt;
NAFDAC REG: 04-4900L` ,

`PRODUCT NAME: TO-TO HEALTH 20 &amp; 40G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,TRECULIA AFRICANA,RAUWOLFIA VORMIORI,TETRALEURA
TETRAPTERA, COLOURANT
BLUE C309006,FRAGRANCE MALABU
&lt;br&gt;
NAFDAC REG: 04-4900L` ,

`PRODUCT NAME: TO-TO HEALTH SOAP 75G
ACTIVE INGREDIENTS: ELAEIS GUINENSIS,BUTYROSPERMUM PARADOXUM,TO-TO
CONCENTRATE,TRECULIA AFRICANA,RAUWOLFIA VORMIORI,TETRALEURA
TETRAPTERA, COLOURANT
BLUE C309006,POTASSIUM HYDROXIDE,PARAFFIN,PARABEN
&lt;br&gt;
NAFDAC REG: 04-4902L` ,

`PRODUCT NAME: DR. KOTTAS KOLDFLU TEA
ACTIVE INGREDIENTS: ELDER FLOWER, LIME FLOWER, FOLIUM PLANTAGINIS, ROSHIP
SHELLS
&lt;br&gt;

NAFDAC REG: A7-0142L` ,

`PRODUCT NAME: CALCEVIT TABLETS
ACTIVE INGREDIENTS: ELEMENTAL CALCIUM 500MG, VIT D3 250 IU
&lt;br&gt;
NAFDAC REG: 4-6157` ,

`PRODUCT NAME: CANAMED VAGINAL
TABLETS
ACTIVE INGREDIENTS: ELEMENTAL CALCIUM 500MG, VIT D3 250 IU
&lt;br&gt;
NAFDAC REG: A4-6158` ,

`PRODUCT NAME: ARISTOCAL-D TABLETS
ACTIVE INGREDIENTS: ELEMENTAL CALCIUM500MG, VITAMIN D 200 IU
&lt;br&gt;
NAFDAC REG: B4-7119` ,

`PRODUCT NAME: HEXAGLOBIN SYRUP (OTC)
ACTIVE INGREDIENTS: ELEMENTAL IRON 10.66MG, CYNOCOBALAMIN 2.5MG
&lt;br&gt;
NAFDAC REG: 04-7901` ,

`PRODUCT NAME: PHARMABOX IRON DEXTRAN INJECTION (POM)
ACTIVE INGREDIENTS: ELEMENTAL IRON 250MG/5ML
&lt;br&gt;
NAFDAC REG: A4-4993` ,

`PRODUCT NAME: MARCFERON SYRUP
ACTIVE INGREDIENTS: ELEMENTAL IRON 30MG, FOLIC ACID 0.5MG/5ML
&lt;br&gt;
NAFDAC REG: B4-6271` ,

`PRODUCT NAME: ORHEPTAL BLOOD TONIC CAPSULES (OTC)
ACTIVE INGREDIENTS: ELEMENTAL IRON 30MG,COPPER 1MG,ZINC 15MG,MANGANESE
3MG,CALCIUM
90MG,MAGNESIUM 45MG,THIAMINE 5MG,VIT B12 1MCG,FOLIC ACID 100MCG
&lt;br&gt;
NAFDAC REG: 04-1405` ,

  `PRODUCT NAME: GARLISULES NATURAL HORIZONS HERBAL CARE CAPSULES
ACTIVE INGREDIENTS: EDIBLE OIL, SOFT GEL CAPSULE CONSTITUENTS
&lt;br&gt;
NAFDAC REG: 04-8960` ,

`PRODUCT NAME: GNLD HOME CARE CONCENTRATED DISINFECTANT
ACTIVE INGREDIENTS: EDTA 5 -15%
&lt;br&gt;
NAFDAC REG: 04-3261` ,

`PRODUCT NAME: STOCRIN TABLETS (POM)
ACTIVE INGREDIENTS: EFAVIRENZ
&lt;br&gt;
NAFDAC REG: 04-7258` ,

`PRODUCT NAME: EFAVIRENZ CAPSULES (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 100MG
&lt;br&gt;
NAFDAC REG: 04-9699` ,

`PRODUCT NAME: AVIRANZ 200MG CAPS (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-6996` ,

`PRODUCT NAME: AVIRANZ CAPSULES (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-6996` ,

`PRODUCT NAME: EFAVIRENZ 200 TABLETS (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: A4-0031` ,

`PRODUCT NAME: EFAZ TABLETS (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: A4-1121` ,

`PRODUCT NAME: EFCURE-200 TABLETS (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;

NAFDAC REG: 04-9505` ,

`PRODUCT NAME: ESTIVA 200 TABLETS (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-5462L` ,

`PRODUCT NAME: ESTIVA 200 TABLETS X 90&#39;S
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-5462L` ,

`PRODUCT NAME: ESTIVA CAPSULES (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-5462` ,

`PRODUCT NAME: POLODIPIN 200 CAPSULES (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-6917 (ADMIN APP)` ,

`PRODUCT NAME: POLODIPIN-200 CAPSULES (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-4917` ,

`PRODUCT NAME: STOCRIN CAPSULES (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 200MG
&lt;br&gt;
NAFDAC REG: 04-7257` ,

`PRODUCT NAME: STOCRIN ORAL SOLUTION
ACTIVE INGREDIENTS: EFAVIRENZ 30MG/ML
&lt;br&gt;
NAFDAC REG: 04-7259` ,

`PRODUCT NAME: EFAVIRENZ CAPSULES (POM)
ACTIVE INGREDIENTS: EFAVIRENZ 50MG
&lt;br&gt;
NAFDAC REG: 04-9698` ,


 `PRODUCT NAME:FELMICAM 2 
    ACTIVE INGREDIENT:PIROXICAM USP 20MG
     <br>
    NAFDAC REG:B4-7412`,
`PROCDUCT NAME: IBUPROFEN TABLETS
ACTIVE INGREDIENTS: IBUPROFEN BP
<br>
NAFDAC REG: B4-6952`,
`PRODUCT NAME: BENYLIN DRY COUGH SYRUP
ACTIVE INGREDIENTS: DEXTROMETHORPHAN 15MG/5ML
<br>
NAFDAC REG: B4-7111`,
`PRODUCT NAME: GEMCITABINE SANDOZ CONCENTRATE SOLUTION FOR INFUSION
ACTIVE INGREDIENTS: GEMCITABINE HYDROCHLORIDE 10MG/ML
<br>
NAFDAC REG: B4-7108`,
`PRODUCT NAME: AIRFLUSAL 50/500 INHALATION POWDER
ACTIVE INGREDIENTS: SALMETEROL 50MCG, FLUTICASONE PROPIONATE 500MCG
<br>
NAFDAC REG: B4-7107`,
`PRODUCT NAME: PARACONICA 1000MG SOLUTION FOR INFUSION
ACTIVE INGREDIENTS: PARACETAMOL 10MG/ML
<br>
NAFDAC REG: B4-7106`,
` PRODUCT NAME: GLIBENCLAMIDE + METFORMIN SANDOZ TABLETS 5MG/500MG
ACTIVE INGREDIENTS: GLIBENCLAMIDE 5NG METFORMIN 500MG
<br>
NAFDAC REG: B4-7105`,
`PRODUCT NAME: HIDRASEC CAPSULES
ACTIVE INGREDIENTS: RACECADOTRIL 100MG
<br>
NAFDAC REG: B4-7104`,


`PRODUCT NAME: HIDRASEC GRANULES FOR ORAL SUSPENSION (INFANTS)
ACTIVE INGREDIENTS: RACECADOTRIL 10MG

<br>
NAFDAC REG: B4-7103`,
`PRODUCT NAME: HIDRASEC GRANULES FOR ORAL SUSPENSION (CHILDREN)
ACTIVE INGREDIENTS: RACECADOTRIL 30MG
<br>
NAFDAC REG: B4-7102`,
`PRODUCT NAME: KRISMOX CAPSULES
ACTIVE INGREDIENTS: AMOXICILLIN 500MG
<br>
NAFDAC REG: B4-7101`,
`PRODUCT NAME: KRISHAT FORTIFIED PROCAINE PENICILLIN POWDER FOR INJECTION
ACTIVE INGREDIENTS: PROCAINE PENICILLIN 3.0G, BENZYL PENICILLIN SODIUM 0.6G
<br>
NAFDAC REG: B4-7100`,
`PRODUCT NAME: DANOXINE TABLETS
ACTIVE INGREDIENTS: SULFADOXINE 500MG, PYRIMETHAMINE 25MG
<br>
NAFDAC REG: B4-7099`,
`PRODUCT NAME: LAMZIDAN TABLET
ACTIVE INGREDIENTS: LAMIVUDINE 150MG, ZIDOVUDINE 300MG
<br>
NAFDAC REG: B4-7098`,
`PRODUCT NAME: KLUSYL ZINC SULPHATE DISPERSIBLE TABLET
ACTIVE INGREDIENTS: ZINC SULPHATE 20MG
<br>
NAFDAC REG: B4-7097`,
`PRODUCT NAME: CODISIN PLUS TABLETS
ACTIVE INGREDIENTS: DIHYDROARTEMISININ 80MG, PIPERAQUINE PHOSPHATE 640MG
<br>
NAFDAC REG: B4-7096`,
`PRODUCT NAME: REMAL TABLETS
ACTIVE INGREDIENTS: DIHYDROARTEMISININ 40MG, PIPERAQUINE PHOSPHATE 320MG
<br>
NAFDAC REG: B4-7095`,
`PRODUCT NAME: DANLODIP TABLETS
ACTIVE INGREDIENTS: AMLODIPINE BESILATE B.P. 10MG
<br>
NAFDAC REG: B4-7094`,
`PRODUCT NAME: POTENZA TABLET
ACTIVE INGREDIENTS: AMLODIPINE 10MG, VALSARTAN 160MG
<br>
NAFDAC REG: B4-7093`,
`PRODUCT NAME: EVERDESTINY PARACETAMOL INJECTION
ACTIVE INGREDIENTS: PARACETAMOL 300MG/2ML
<br>
NAFDAC REG: B4-7092`,
`PRODUCT NAME: EVERFENAC INJECTION
ACTIVE INGREDIENTS: DICLOFENAC SODIUM 75MG/3ML
<br>
NAFDAC REG: B4-7091`,
`PRODUCT NAME: BEXALOL STERILE EYE DROP
ACTIVE INGREDIENTS: BETAXOLOL 0.25%
<br>
NAFDAC REG: B4-7090`,
`PRODUCT NAME: EVERDESTINY DEXAMETHASONE SODIUM PHOSPHATE INJECTION
ACTIVE INGREDIENTS: DEXAMETHASONE SODIUM PHOSPHATE 4MG/ ML
<br>
NAFDAC REG: B4-7089`,
`PRODUCT NAME: FASEC-3-KIT
ACTIVE INGREDIENTS: FLUCONAZOLE 150MG, AZITHROMYCIN 1G, SECNIDAZOLE 1G
<br>
NAFDAC REG: B4-7088`,

`PRODUCT NAME: DANTHROMYCIN TABLETS
ACTIVE INGREDIENTS: AZITHROMYCIN USP 250MG
<br>
NAFDAC REG: B4-7087`,
`PRODUCT NAME: DAYATRIM PAEDIATRIC POWDER FOR ORAL SUSPENSION
ACTIVE INGREDIENTS: SULFAMETHOXAZOLE BP 200MG, TRIMETHOPRIM BP 40MG/5ML
<br>
NAFDAC REG: B4-7086`,
`PRODUCT NAME: EVERDESTINY BENZYL PENICILLIN SODIUM POWDER FOR INJECTION
ACTIVE INGREDIENTS: BENZYL PENICILLIN SODIUM 1,000,000 IU
<br>
NAFDAC REG: B4-7085`,
`PRODUCT NAME: EVERDESTINY AMOXICILLIN SODIUM POWDER FOR INJECTION
ACTIVE INGREDIENTS: AMOXICILLIN 500MG
<br>
NAFDAC REG: B4-7084`,
`PRODUCT NAME: EVERDESTINY FORTIFIED PROCAINE PENICILLIN INJECTION
ACTIVE INGREDIENTS: PROCAINE PENICILLIN 3,000,000 IU, BENZYL PENICILLIN 1,000,000 IU/VIAL
<br>
NAFDAC REG: B4-7083`,
`PRODUCT NAME: EVERDESTINY STREPTOMYCIN SULPHATE POWDER FOR INJECTION
ACTIVE INGREDIENTS: STREPTOMYCIN SULPHATE 5G
<br>
NAFDAC REG: B4-7082`,
`PRODUCT NAME: DARVINKS GENTAMYCIN SULFATE INJECTION
ACTIVE INGREDIENTS: GENTAMYCIN SULFATE 80MG/2ML
<br>
NAFDAC REG: B4-7081`,

`PRODUCT NAME: BSMITH HYOSCINE BUYTLBROMIDE INJECTION
ACTIVE INGREDIENTS: HYOSCINE BUTYLBROMIDE 10MG/ML
<br>
NAFDAC REG: B4-7080`,
`PRODUCT NAME: TEKAGRA ORAL JELLY (ORANGE FLAVOUR)
ACTIVE INGREDIENTS: SILDENAFIL CITRATE
<br>
NAFDAC REG: B4-6967`,
`PRODUCT NAME: ATORVASTATIN TABLETS
ACTIVE INGREDIENTS: ATORVASTATIN
<br>
NAFDAC REG: B4-6966`,
`PRODUCT NAME: ATORVASTATIN TABLETS
ACTIVE INGREDIENTS: ATORVASTATIN 20MG
<br>
NAFDAC REG: B4-6965`,
`PRODUCT NAME: PLEXITONE CAPSULES
ACTIVE INGREDIENTS: ELEMENTAL IRON, ZINC SULPHATE, CYANOCOBALAMIN, FOLIC ACID & ABSCORBIC ACID
<br>
NAFDAC REG: B4-6964`,
`PRODUCT NAME: TRAMADOL CAPSULES
ACTIVE INGREDIENTS: TRAMADOL HYDROCHLORIDE BP:
<br>
NAFDAC REG: B4-6963`,
`PRODUCT NAME: ATRACURIUM INJECTION
ACTIVE INGREDIENTS: ATRACURIUM BESILATE USP
<br>
NAFDAC REG: B4-6961`,
`PRODUCT NAME: SILDENAFIL TABLET
ACTIVE INGREDIENTS: SILDENAFIL CITRATE

<br>
NAFDAC REG: B4-6960`,
`PRODUCT NAME: SIMBAGRA TABLETS
ACTIVE INGREDIENTS: SILDENAFIL CITRATE
<br>
NAFDAC REG: B4-6959`,
`PRODUCT NAME: LT-SILDENAFIL TABLET
ACTIVE INGREDIENTS: SILDENAFIL CITRATE
<br>
NAFDAC REG: B4-6957`,
`PRODUCT NAME: OMEPRAZOLE CAPSULES (FORMERLY: OMEPRABASE)
ACTIVE INGREDIENTS: GASTRO-RESISTANT OMEPRAZOLE BP
<br>
NAFDAC REG: B4-6956`,
`PRODUCT NAME: COLTEX SYRUP
ACTIVE INGREDIENTS: DEXTROMETHORPHAN HYDROBROMIDE , GUAIFENESINE G, CHLOROPHENIRAMINE
MALEATE
<br>
NAFDAC REG: B4-6955`,
`PRODUCT NAME: DAILYVIT CAPSULES
ACTIVE INGREDIENTS: MULTIVITAMIN & MINERALS
<br>
NAFDAC REG: B4-6949`,
`PRODUCT NAME: AYOLAEMSTIFER SYRUP
ACTIVE INGREDIENTS: FERROUS GLYCINE SULPHATE, AMINO ACID, VITAMINS & MINERALS
<br>
NAFDAC REG: B4-6948`,
`PRODUCT NAME: MACDECH AMINOPHYLLINE TABLETS
ACTIVE INGREDIENTS: AMINOPHYLLINE BP
<br>
NAFDAC REG: B4-6947`,

`PRODUCT NAME: ACYCLOVIR TABLETS
ACTIVE INGREDIENTS: ACYCLVIR USP
<br>
NAFDAC REG: B4-6944`,
`PRODUCT NAME: ISONIAZID TABLETS
ACTIVE INGREDIENTS: ISONIAZID BP
<br>
NAFDAC REG: B4-6943`,
`PRODUCT NAME: HEXIGEL ANISEPTIC MOUTH GEL
ACTIVE INGREDIENTS: CHLORHEXIDINE GLUCONATE
<br>
NAFDAC REG: B4-6942`,
`PRODUCT NAME: FECCOX ARTEMETHER INJECTION
ACTIVE INGREDIENTS: ARTEMETHER
<br>
NAFDAC REG: B4-6941`,
`PRODUCT NAME: E.D.P QUININE TABLETS
ACTIVE INGREDIENTS: QUININE SULPHATE BP
<br>
NAFDAC REG: B4-6940`,
`PRODUCT NAME: SAFERIA SOFTGEL CAPSULES
ACTIVE INGREDIENTS: ARTEMETHERLUMEFANTRINE
<br>
NAFDAC REG: B4-6939`,
`PRODUCT NAME: GEBETHER INJECTION
ACTIVE INGREDIENTS: ARTEMETHER
<br>
NAFDAC REG: B4-6938`,
`PRODUCT NAME: LOSRTEC TABLETS
ACTIVE INGREDIENTS: LOSARTAN POSSIUM USP

<br>
NAFDAC REG: B4-6936`,
`PRODUCT NAME: DANZEL TABLETS
ACTIVE INGREDIENTS: ALBENDAZOLE BP
<br>
NAFDAC REG: B4-6933`,
`PRODUCT NAME: ALBENDAZOLE TABLETS
ACTIVE INGREDIENTS: ALBENDAZOLE BP
<br>
NAFDAC REG: B4-6932`,
`PRODUCT NAME: SUCROPHAGE TABLETS
ACTIVE INGREDIENTS: METFORFIN HYDROCHLORIDE
<br>
NAFDAC REG: B4-6931`,
`PRODUCT NAME: BETAMETHASONE & NEOMYCIN EYE/EAR DROPS
ACTIVE INGREDIENTS: BETAMETHASONE SODIUM PHOSPHATE BP & NEOMYCIN SULPHATE BP
<br>
NAFDAC REG: B4-6930`,
`PRODUCT NAME: CIPROPTIC EYE/EAR DROPS
ACTIVE INGREDIENTS: CIPROFLOXACIN
<br>
NAFDAC REG: B4-6929`,
`PRODUCT NAME: TRAFIX DISPERSIBLE TABLETS
ACTIVE INGREDIENTS: CEFIXIME USP
<br>
NAFDAC REG: B4-6928`,
`PRODUCT NAME: AMOXICILLIN & CLAVULANIC ACID TABLETS
ACTIVE INGREDIENTS: AMXICILLING & CLAVULANIC ACID
<br>
NAFDAC REG: B4-6927`,

`PRODUCT NAME: AZITHROMYCIN POWDER FOR ORAL SUSPENSION
ACTIVE INGREDIENTS: AZITHROMYCIN
<br>
NAFDAC REG: B4-6925`,
`PRODUCT NAME: XYMENTIN DISPERSIBLE TABLETS
ACTIVE INGREDIENTS: AMOXICILLIN & CLAVULANIC ACID
<br>
NAFDAC REG: B4-6924`,
`PRODUCT NAME: ERLICIN 500 TABLETS
ACTIVE INGREDIENTS: ERYTHROMYCIN STEARATE BP
<br>
NAFDAC REG: B4-6922`,
`PRODUCT NAME: CEFUROXIME AXETIL TABLETS
ACTIVE INGREDIENTS: CEFUROXIME AXETIL USP
<br>
NAFDAC REG: B4-6921`,
`PRODUCT NAME: SUNYMET ERYTHROMYCIN TABLETS
ACTIVE INGREDIENTS: ERYTHROMYCIN STEARATE BP
<br>
NAFDAC REG: B4-6920`,
`PRODUCT NAME: AMOXICILLIN, CLAVULANIC ACID TABLETS
ACTIVE INGREDIENTS: AMOXICILLING , POATSSIUM CLAVULANATE BP
<br>
NAFDAC REG: B4-6919`,
`PRODUCT NAME: DORPROFLUX INJECTION
ACTIVE INGREDIENTS: CIPROFLOXACIN USP
<br>
NAFDAC REG: B4-6918`,
`PRODUCT NAME: DORMETRO INJECTION
ACTIVE INGREDIENTS: METRONIDAZOLE USP

<br>
NAFDAC REG: B4-6917`,
`PRODUCT NAME: MAYDON CEFIXIME TABLETS
ACTIVE INGREDIENTS: CEFIXIME USP
<br>
NAFDAC REG: B4-6916`,
`PRODUCT NAME: PRILIGY 60MG TABLETS
ACTIVE INGREDIENTS: DAPOXETINE
<br>
NAFDAC REG: B4-6915`,
`PRODUCT NAME: PRILIGY 30MG TABLETS
ACTIVE INGREDIENTS: DAPOXETINE
<br>
NAFDAC REG: B4-6914`,
`PRODUCT NAME: BICALUTAMIDE SANDOZ 150MG TABLETS
ACTIVE INGREDIENTS: BICALUTAMIDE
<br>
NAFDAC REG: B4-6913`,
`PRODUCT NAME: BICALUTAMIDE SANDOZ 50MG TABLETS
ACTIVE INGREDIENTS: BICALUTAMIDE
<br>
NAFDAC REG: B4-6912`,

`PRODUCT NAME: PAROXETINE SANDOZ TABLETS
ACTIVE INGREDIENTS: PAROXETINE HYDOCHLORIDE
<br>
NAFDAC REG: B4-6911`,
`PRODUCT NAME: ARTROSAN TABLETS
ACTIVE INGREDIENTS: MELOXICAM
<br>

NAFDAC REG: B4-6910`,
`PRODUCT NAME: VINCO GENTAMYCIN INJECTION
ACTIVE INGREDIENTS: GENTAMYCIN L
<br>
NAFDAC REG: B4-6909`,
`PRODUCT NAME: IMMUNBOOST EFFERVESCENT TABLET
ACTIVE INGREDIENTS: VITAMIN C
<br>
NAFDAC REG: B4-6908`,
`PRODUCT NAME: AMOXICILLIN 500MG & CLAVULANATE POTASSIUM 125MG TABLETS
ACTIVE INGREDIENTS: AMOXICILLIN CLAVULANATE POTASSIUM
<br>
NAFDAC REG: B4-6907`,
`PRODUCT NAME: BJ CHOICE GENTAMYCIN INJECTION
ACTIVE INGREDIENTS: GENTAMYCIN
<br>
NAFDAC REG: B4-6906`,
`PRODUCT NAME: METFORAL 500MG TABLETS
ACTIVE INGREDIENTS: METFORMIN HYDROCHLORIDE
<br>
NAFDAC REG: B4-6904`,
`PRODUCT NAME: METFORAL 1000MG TABLETS
ACTIVE INGREDIENTS: METFORMIN HYDROCHLORIDE
<br>
NAFDAC REG: B4-6903`,
`PRODUCT NAME: SOMAZINA ORAL SOLUTION 1000MG
ACTIVE INGREDIENTS: CITICOLINE SODIUM
<br>
NAFDAC REG: B4-6901`,
`PRODUCT NAME: ACOFIX POWDER FOR ORAL SUSPENSION

ACTIVE INGREDIENTS: CEFIXIME USP
<br>
NAFDAC REG: B4-6889`,
`PRODUCT NAME: OXYNIC 1000 TABLETS
ACTIVE INGREDIENTS: AMOXICILLIN & POTASSIUM CLAVULANATE BP
<br>
NAFDAC REG: B4-6874`,
`PRODUCT NAME: KENOP 228.5 POWDER FOR ORAL SUSPENSION
ACTIVE INGREDIENTS: AMOXICILLIN CLAVULANIC ACID
<br>
NAFDAC REG: B4-6829`,
`PRODUCT NAME: ALUMINA, MAGNESIUM & SIMETHICONE ORAL SUSPENSION
ACTIVE INGREDIENTS: ALUMINIUM HYDROXIDE 225MG/5ML, MAGNESIUM HYDROXIDE SIMETHICONE
<br>
NAFDAC REG: B4-6828`,
`PRODUCT NAME: DANMETHER POWDER
ACTIVE INGREDIENTS: ARTEMETHER 20MG, LUMEFANTRINE 120MG
<br>
NAFDAC REG: B4-6489`,
`PRODUCT NAME: DANMETHER TABLETS
ACTIVE INGREDIENTS: ARTEMETHER 20MG, LUMEFANTRINE 120MG
<br>
NAFDAC REG: B4-6488` ,
`PRODUCT NAME: SPAQ-C0 DISPERSIBLE TABLETS (500MG/25MG) + (153MG)
ACTIVE INGREDIENTS: SULFADOXINEPYRIMETHAMINEG + AMODIAQUIN
<br>
NAFDAC REG: B4-6482`,
`PRODUCT NAME: SPAQ-C0 DISPERSIBLE TABLETS (250MG/12.5MG) + (76.5MG)
ACTIVE INGREDIENTS: SULFADOXINE PYRIMETHAMINE + AMODIAQUINE
<br>

NAFDAC REG: B4-6481`,
`PRODUCT NAME: LUMAPIL FORTE TABLET [ FORMERLY PHAMATEX ARTHEMETER/LUMEFANTRINE TABLET]
ACTIVE INGREDIENTS: ARTEMETHER 80MG, LUMEFANTRINE 480MG
<br>
NAFDAC REG: B4-2275`,
`PRODUCT NAME: SOFTHEALTH DICLOFENAC POTASSIUM TABLETS
ACTIVE INGREDIENTS: DICLOFENAC POTASSIUM
<br>
NAFDAC REG: B4-6816`,
`PRODUCT NAME: SOFTHEALTH OMEPRAZOLE CAPSULES
ACTIVE INGREDIENTS: OMEPRAZOLE BP
<br>
NAFDAC REG: B4-6820`,
`PRODUCT NAME: EMMAN TABLETS
ACTIVE INGREDIENTS: DIYDROARTEMISININ , PIPERAQUINE PHOSPHATE
<br>
NAFDAC REG: B4-6815`,
`PRODUCT NAME: RHYZOMIN SYRUP
ACTIVE INGREDIENTS: AMINO ACIDS & VITAMINS
<br>
NAFDAC REG: B4-6814`,
`PRODUCT NAME: TROVAC TABLETS
ACTIVE INGREDIENTS: FERROUS ASCORBATE, FOLIC ACID , ZINC SULFATE
<br>
NAFDAC REG: B4-6813`,
`PRODUCT NAME: METFOSYN 1000 SR TABLETS
ACTIVE INGREDIENTS: METFORMIN HYDROCHLORIDE BP
<br>
NAFDAC REG: B4-6812`,
`PRODUCT NAME: ZADIP ORS

ACTIVE INGREDIENTS: SODIUM CHLORIDE POTASSIUM CHLORIDE, SODIUM CITRATE ANHYDROUS GLUCOSE
<br>
NAFDAC REG: B4-6811`,
`PRODUCT NAME: MIRAL ALBENDAZOLE 200 TABLETS
ACTIVE INGREDIENTS: ALBENDAZOLE USP
<br>
NAFDAC REG: B4-6810`,
`PRODUCT NAME: MIRAL ALBENDAZOLE SUSPENSION
ACTIVE INGREDIENTS: ALBENDAZOLE USP
<br>
NAFDAC REG: B4-6809`,
`PRODUCT NAME: ANTALGEXT CAPSULES
ACTIVE INGREDIENTS: PARACETAMOL TRAMADOL HYDROCHLORID
<br>
NAFDAC REG: B4-6808`,
`PRODUCT NAME: SOFTHEALTH PIROXICAM CAPSULES
ACTIVE INGREDIENTS: PAIN & INFLAMMATION
<br>
NAFDAC REG: B4-6818`,
`PRODUCT NAME: HILTOP TABLETS
ACTIVE INGREDIENTS: TOPIRAMATE
<br>
NAFDAC REG: B4-6823`,
`PRODUCT NAME: DIOARTEM 20/120 TABLETS
ACTIVE INGREDIENTS: ARTEMETHER LUMEFANTRINE
<br>
NAFDAC REG: B4-6807`,
`PRODUCT NAME: HY & G ARTEMETHER INJECTION
ACTIVE INGREDIENTS: ARTEMETHER
<br>
NAFDAC REG: B4-6806`,

`PRODUCT NAME: WAPHEXIN INJECTION
ACTIVE INGREDIENTS: FLUPHENAZINE DECANOATE USP
<br>
NAFDAC REG: B4-6805`,
`PRODUCT NAME: MILTON RISPERIDONE TABLETS
ACTIVE INGREDIENTS: RISPERIDONE USP
<br>
NAFDAC REG: B4-6804`,
`PRODUCT NAME: EDEN LISINOPRIL 5MG TABLETS
ACTIVE INGREDIENTS: LISINOPRIL USP
<br>
NAFDAC REG: B4-6803`,
`PRODUCT NAME: BARAXIX TABLETS
ACTIVE INGREDIENTS: FRUSEMIDE B.P.
<br>
NAFDAC REG: B4-6802`,
`PRODUCT NAME: EDEN LISINOPRIL 10MG TABLETS
ACTIVE INGREDIENTS: LISINOPRIL USP
<br>
NAFDAC REG: B4-6801`,
`PRODUCT NAME: POCCOSART TABLETS
ACTIVE INGREDIENTS: VALSARTAN , AMLODIPINE
<br>
NAFDAC REG: B4-6800`,
`PRODUCT NAME: VIRBETOL CAPSULES
ACTIVE INGREDIENTS: RIBAVARIN USP
<br>
NAFDAC REG: B4-6797`,
`PRODUCT NAME: POCCOTEL TABLETS

ACTIVE INGREDIENTS: TELMISARTAN USP , HYDROCHLOROTHIAZIDE USP
<br>
NAFDAC REG: B4-6799`,
`PRODUCT NAME: JOHNBEE FLUCONAZOLE TABLETS
ACTIVE INGREDIENTS: FLUCONAZOLE USP
<br>
NAFDAC REG: B4-6796`,
`PRODUCT NAME: JOHNBEE AZITHROMYCIN TABLETS
ACTIVE INGREDIENTS: AZITHROMYCIN
<br>
NAFDAC REG: B4-6795`,
`PRODUCT NAME: AZITROMA ORAL SUSPENSION
ACTIVE INGREDIENTS: AZITHROMYCIN DIHYDRATE USP EQ TO AZITHROMYCIN
<br>
NAFDAC REG: B4-6793`,
`PRODUCT NAME: UPNAT TABLETS
ACTIVE INGREDIENTS: CEFFUROXIME AXETIL USP EQ TO CEFUROXIME
<br>
NAFDAC REG: B4-6792`,
`PRODUCT NAME: JOHNBEE ERYTHROMYCIN TABLETS
ACTIVE INGREDIENTS: ERYTHROMYCIN STEARATE BP
<br>
NAFDAC REG: B4-6791`,
`PRODUCT NAME: C-ZOCAIN PLUS
ACTIVE INGREDIENTS: LIDOCAINE CHLORIDE BP ADRENALINE
<br>
NAFDAC REG: B4-6790`,
`PRODUCT NAME: ICHIDAN CREAM
ACTIVE INGREDIENTS: SALICYLIC ACID BP BENZOIC ACID BP
<br>

NAFDAC REG: B4-6789`,
`PRODUCT NAME: COMBISUNATE 80/480 TABLETS
ACTIVE INGREDIENTS: ARTEMETHER , LUMEFANTRINE
<br>
NAFDAC REG: A4-5551`,
`PRODUCT NAME: VARSPAR TABLET
ACTIVE INGREDIENTS: AMLODIPINE 5MG (AS AMLODIPINE BESILATE)
<br>
NAFDAC REG: A4-5476`,
`PRODUCT NAME: BIOMEGRACIN TABLET
ACTIVE INGREDIENTS: LEVOFLOXACIN USP
<br>
NAFDAC REG: A4-5272`,
`PRODUCT NAME: RUBILON 50 POWDER FOR INJECTION
ACTIVE INGREDIENTS: EPIRUBICIN HYDROCHLORIDE
<br>
NAFDAC REG: A4-4989`,
`PRODUCT NAME: GALWAYS TACORANGE DROPS VITAMIN C
ACTIVE INGREDIENTS: ASCORBIC ACID
<br>
NAFDAC REG: A4-4522`,
`PRODUCT NAME: BENAZINE INJECTION
ACTIVE INGREDIENTS: PENTAZOCINE LACTATE BP PENTAZOCINE
<br>
NAFDAC REG: A4-3854`,
`PRODUCT NAME: NORMODIPIN TABLET
ACTIVE INGREDIENTS: NIFEDIPINE USP
<br>
NAFDAC REG: A4-3639`,



  ];
  

  const searchInput = document.getElementById('search');
  const searchWrapper = document.querySelector('.wrapper');
  const resultsWrapper = document.querySelector('.results');
  
  searchInput.addEventListener('keyup', () => {
    let results = [];
    let input = searchInput.value;
    if (input.length) {
      results = searchable.filter((item) => {
        return item.toLowerCase().includes(input.toLowerCase());
        
      });
    }
    renderResults(results);
    
  });
  
  function renderResults(results) {
    if (!results.length) 
    //return searchWrapper.classList.remove('show');
    {alert(`NOT REGISTERED`);
     
    }
  
    const content = results
      .map((item) => {
        return `<li><div>${item}</div></li>`;
      })
      .join('');
  
    searchWrapper.classList.add('show');
    resultsWrapper.innerHTML = `<ul>${content}</ul>`;

    
  };
  

  //form
function validateForm() {
  //gets the name
  let name = document.getElementById("contact-name").value;
  //gets the email
  let email = document.getElementById("contact-email").value;
  //gets the message
  let message = document.getElementById("contact-message").value;
  let number = document.getElementById("contact-number").value;
  //checks if all fields have been filled before sending message.
  if (name.trim() == "" || email.trim() == "" || message.trim() == "" || Number.trim()=="") 
  {
    alert("all fields must be filled");
  } else {
    sendMessage(name, email, message);
  }

  document.getElementById("send").addEventListener("click", validateForm);

}





//highlighgt

 
const highlightMenu = () => {
    const elem = document.querySelector('.highlight');
    const homeMenu = document.querySelector('#home');
    const aboutMenu = document.querySelector('#about');
    const servicesMenu = document.querySelector('#contact-details');
    let scrollPos = window.scrollY;
    window.addEventListener('click', highlightMenu);

   window.addEventListener('scroll', highlightMenu);


}
    // console.log(scrollPos);
  
    // adds 'highlight' class to my menu items
    
 
 
  
